
#bring in the library that I will be working with
library(shiny)
 library(ggplot2)
 library(readxl)
 library(tidyverse)
 library(rhandsontable)
 library(shinyalert)
 library(shinydashboard)
 library(htmltools)
 library(leaflet)
 library(slickR) #new install on land and water linex

library(shinyWidgets)

library(vroom) #new install on land and water linex





# Define UI 


  
#########################################################################################################
###############                       navbartitle                          #################################
#########################################################################################################
 
  
   ui <- (navbarPage(title = '', collapsible = TRUE,
                    
                     
                      header = tagList(    
                        useShinydashboard()
                     ) ,   ## these two lines get the value box to display without using shinydashboards        

                     
#########################################################################################################
#########################################################################################################
###############                       what is my constraint page                     #################################
#########################################################################################################                 


tabPanel("What is my constraint", #tab title pageleafletOutput("map"),
         fluidPage( 
           fluidRow(
             box(
               title = "Water repellence", width = 6, solidHeader = TRUE, status = "primary",
               tags$b("Water repellence forms when waxes from decayed organic material (e.g. stubbles) coat grains of soil, making them repel water, which inhibits water entry into the soil profile. This leads to patchy crop establishment and a staggered germination of weeds, reducing yield potential at the start of the season."),  
               tags$br(), #this is a break
               #tags$img(src = "water drop.jpg"), #need to resize this image
               tags$img(src = "wheat.jpg"),
               tags$br(), #this is a break
               tags$a(href="13 July 2022 - Water Repellence and pH in Sandy Soils.pdf", ## this documnet need to sit inside the app directory in a folder called www
                      "click here for more info on water repllency" )
             ), #box water repellency
             
             
             box(
               title = "Nutrition", width = 6, solidHeader = TRUE, status = "primary",
               tags$b("Sandy soils are often nutrient deficient or infertile because they are highly weathered soils which are low in carbon and have a poor ability to retain and cycle nutrients. The realisation of the crop yield potential generated by amelioration of sands relies on adequate crop nutrition to feed the new yield potential. There are some key considerations when assessing nutrient status:"),
               tags$br(), #this is a break
               tags$img(src = "wheat.jpg"), 
               tags$br(), #this is a break
               tags$a(href="13 July 2022 - Diagnosing nutritional constraints in sandy soils.pdf", ## this documnet need to sit inside the app directory in a folder called www
                      "click here for more info on nutritional constraints" ),
               
             ), #box Nutrition
             box(
               title = "Acid", width = 6, solidHeader = TRUE, status = "primary",
               tags$b("pH is a measure of the concentration of hydrogen (H+) and hydroxyl (OH-) ions in a soil solution and indicates that a soil is acidic (low pH), neutral or alkaline (high pH).  pH variation through the soil profile can occur. It’s important to understand this variation as nutrient availability and crop type tolerance can be affected, resulting in potential plant deficiencies or toxicities."),
               tags$br(), #this is a break
               #tags$img(src = "pH_chart.jpg"), #wrong size
               tags$img(src = "wheat.jpg"),
               tags$br(), #this is a break
               tags$a(href="13 July 2022 - Water Repellence and pH in Sandy Soils.pdf", ## this documnet need to sit inside the app directory in a folder called www
                      "click here for more info on acidity" )
             ), #box acid
             box(
               title = "High soil strength", width = 6, solidHeader = TRUE, status = "primary",
               tags$b("High soil strength can be caused by compaction and/or hard setting and can severely limit plant root penetration through the soil, preventing access to deep reserves of soil moisture and nutrients. A hydraulic cone penetrometer is the simplest tool to use to measure soil strength. It measures the force required to insert a standard cone into the soil, reported as either kiloPascals (kPa) or megaPascals (1 MPa = 1000 kPa)."),
               tags$br(), #this is a break
               tags$img(src = "wheat.jpg"), 
               tags$br(), #this is a break
               tags$a(href="13 July 2022_High Soil Strength in Sandy Soils .pdf", ## this documnet need to sit inside the app directory in a folder called www
                      "click here for more info on high soil strength" )
             ) #box acid
             
           ), #fluid row     
           
           hr(),
           
           
           
           
           
           
           
           
           
         ), #tabPanel landing page bracket
),  #fluid page

#########################################################################################################
                    
#########################################################################################################
###############                       tab 1                           #################################
#########################################################################################################                 
                    

                     tabPanel("Trial results", #tab title pageleafletOutput("map"),
                              leafletOutput("map"),


                      fluidRow(

                             column(width = 6,
                               selectInput(
                                 "site_selection",
                                 label = h3("select site:"),
                                 choices = list(
                                   "Brimpton Lake",
                                   "Brooker",
                                   "Buckleboo",
                                   "Bute_CSIRO",
                                   "Bute_Trengrove",
                                   "Cadgee",
                                   "Carwarp_Amelioration",
                                   "Cummins",
                                   "Karkoo",
                                   "Karoonda",
                                   "Kooloonong_canola",
                                   "Kooloonong_chickpea",
                                   "Kooloonong_lentil",
                                   "Kooloonong_lupin",
                                   "Kybunga",
                                   "Lowaldie_Crest",
                                   "Lowaldie_Deep sand",
                                   "Malinong",
                                   "Monia_Gap",
                                   "Mt Damper",
                                   "Murlong",
                                   "Ouyen_Placement",
                                   "Ouyen_Spade",
                                   "Sherwood",
                                   "Telopea_Downs",
                                   "Tempy",
                                   "Waikerie",
                                   "Warnertown",
                                   "Wynarka",
                                   "Yenda",
                                   "Younghusband"
                                   
                              ),
                                  selected = "Brooker"),
                             ),#bracket for select input
                             ),#fluid row bracket #1

                             fluidRow(
                               column(8,
                                      #align = "center",
                                      offset =.5,
                                      tags$a(href="shorthand trial name_v2.pdf", ## this documnet need to sit inside the app directory in a folder called www
                                      
                                    "click here for more info on trial names" )
                               )#clm bracket
                             ),#fluid row bracket #2

                              fluidRow(
                               column(width=6,   DT::dataTableOutput("trial_table")),
                               column(width = 6,  plotOutput("trial_plot"))

                                ),#fluid row bracket #3
                      
                      ###Temp code##
                      # fluidRow(
                      #   column(width=6,   verbatimTextOutput("site_selection"))
                      # 
                      # ),#fluid row bracket #4 Which is just temp

                             ), #tabPanel1 bracket


#########################################################################################################
###############                       tab 2                           #################################
#########################################################################################################                 
tabPanel("comparision with trial", #tab title page
             
         
  
############################################################################################################
#################                  options to filter the data       ########################################
############################################################################################################
  
    
    fluidRow(
      box(
        title = "Site", width = 4, solidHeader = TRUE, status = "primary",

        uiOutput("data2"),

        useShinyalert(),actionButton("use_page", "How to use this page"),
        tags$a(href="Undiscounted cash flow.pdf", "More information on model"),
      ), #box sites


      box(
        title = "Constraint", width = 8, solidHeader = TRUE, status = "primary",

        infoBoxOutput("non_wetting"),
        infoBoxOutput("acidic"),
        infoBoxOutput("physical"),
        valueBoxOutput("rainfall")

      ) #box Constraint
    ),#fluid row 1




    fluidRow(
      column(width=6, uiOutput("data1_scen1")),   ## uiOutput - gets the UI from the server
      column(width=6, uiOutput("data1_scen2"))   #remove on of this one?
    ),#fluid row bracket 2

    ############################################################################################################
    ##############################            the tables         ###############################################
    ############################################################################################################
    ## Cost table
    fluidRow(
      column(width=6,h2("Cost of modification Scenario 1")),

      column(width=6,h2("Cost of modification Scenario 2"))
    ),#fluid row bracket 2
    fluidRow(
      column(width=6,rHandsontableOutput("cost_sc1")),
      column(width=6,rHandsontableOutput("cost_sc2"))
    ),#fluid row bracket 3

    ## Yield table
    fluidRow(
      column(width=6,h2("Yield t/ha Scenario 1")),
      column(width=6,h2("Yield t/ha Scenario 2"))
    ),#fluid row bracket 4
    fluidRow(
      column(width=6,rHandsontableOutput("yld_sc1")),
      column(width=6,rHandsontableOutput("yld_sc2"))
    ),#fluid row bracket 5

    ## Extra table
    fluidRow(
      column(width=6,h2("Extra cost or benefits Scenario 1")),
      column(width=6,h2("Extra cost or benefits Scenario 2"))
    ),#fluid row bracket 6
    fluidRow(
      column(width=6,rHandsontableOutput("extra_sc1")),
      column(width=6,rHandsontableOutput("extra_sc2"))
    ),#fluid row bracket 7

    ############################################################################################################
    ##############################            results         ###############################################
    ############################################################################################################

    #select number of years
    fluidRow(
      column(width=6,selectInput("years", label = h3("years for analysis"),
                                 choices = list("1 Year" = 1, "2 Year" = 2, "3 Year" = 3,
                                                "4 Year" = 4, "5 Year" = 5),
                                 selected = 3))
    ),#fluid bracket 8

    #heading for results
    fluidRow(
      column(width=12,h2("Results Scenario 1 and 2"))
    ),#fluid row bracket 9

    fluidRow(
      column(width=6,plotOutput("plot1"))
    ),#fluid row bracket 10

    fluidRow(
      column(width=6,DT::dataTableOutput("economic_tb1")) #this is just a check
    ),#fluid row bracket 11

    ############################################################################################################
    ##############################            save data buttons         ###########################################
    ############################################################################################################
      fluidRow(downloadButton("download",
                        label = "Download data table"))#fluid row bracket 12

    ############################################################################################################
    ##############################            end of UI              ###########################################
    ############################################################################################################
#####################       end of UI for the comparision        ###########################################
############################################################################################################

) #tabPanel2 bracket

   ) #navbar bracket
   ) # ui bracket
   


